
Vagrant.configure(2) do |config|
  config.vm.box = "guvnor-node-4.x"

  #config.vm.network :forwarded_port, guest: 8001, host: rand(30000) + 30000
  config.vm.network :forwarded_port, guest: 8001, host: 30028

  config.vm.synced_folder "../../../../lib", "/opt/guvnor/lib"
  config.vm.synced_folder "../../../../test", "/opt/guvnor/test"
  config.vm.synced_folder "../../../../docker", "/docker"

  # config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
end
