#!/bin/bash
### BEGIN INIT INFO
# Provides: boss
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Boss init script
# Description: Boss is a process manager for Node.js
### END INIT INFO

NAME=boss
RETVAL=0

# Find node on the path
NODE=`which node`

if [[ ! -x "$NODE" ]]
then
  NODE=/usr/local/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  NODE=/usr/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  NODE=/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  echo "Node could not be found! Is it installed on this system?"
  exit 1
fi

# Find boss on the path
BOSS=`which bs`

if [[ ! -x "$BOSS" ]]
then
  BOSS=/usr/local/bin/bs
fi

if [[ ! -x "$BOSS" ]]
then
  BOSS=/usr/local/lib/node_modules/process-boss/bin/bs
fi

if [[ ! -x "$BOSS" ]]
then
  echo "Boss could not be found! Is it installed on this system?"
  exit 1
fi

# Ask boss which user we should start it as
USER=`$BOSS config boss.user`

boss() {
    su - $USER -c "PATH=$PATH;$NODE $BOSS $*"
}

start() {
    echo "Starting $NAME"
    boss list
}

stop() {
    echo "Stopping $NAME"
    boss kill
}

restart() {
    stop
    start
}

status() {
    boss status
    RETVAL=$?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
