#!/bin/bash
### BEGIN INIT INFO
# Provides: guvnor
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Should-Start: $network
# Should-Stop: $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Guvnor init script
# Description: Guvnor is a process manager for Node.js
### END INIT INFO

NAME=guvnor
RETVAL=0

# Find node on the path
NODE=`which node`

if [[ ! -x "$NODE" ]]
then
  NODE=/usr/local/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  NODE=/usr/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  NODE=/bin/node
fi

if [[ ! -x "$NODE" ]]
then
  echo "Node could not be found! Is it installed on this system?"
  exit 1
fi

# Find guvnor on the path
GUVNOR=`which guvnor`

if [[ ! -x "$GUVNOR" ]]
then
  GUVNOR=/usr/local/bin/guvnor
fi

if [[ ! -x "$GUVNOR" ]]
then
  GUVNOR=/usr/bin/guvnor
fi

if [[ ! -x "$GUVNOR" ]]
then
  GUVNOR=/usr/local/lib/node_modules/guvnor/bin/guvnor
fi

if [[ ! -x "$GUVNOR" ]]
then
  GUVNOR=/usr/lib/node_modules/guvnor/bin/guvnor
fi

if [[ ! -x "$GUVNOR" ]]
then
  echo "Guvnor could not be found! Is it installed on this system?"
  exit 1
fi

# Ask guvnor which user we should start it as
USER=`$GUVNOR config guvnor.user`

guvnor() {
    su - $USER -c "PATH=$PATH;$NODE $GUVNOR $*"
}

start() {
    echo "Starting $NAME"
    guvnor list
}

stop() {
    echo "Stopping $NAME"
    guvnor kill
}

restart() {
    stop
    start
}

status() {
    guvnor status
    RETVAL=$?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
